# Generated by Django 2.2.8 on 2021-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('idade', models.IntegerField(max_length=3, verbose_name='idade')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('apelido', models.CharField(max_length=100, verbose_name='apelido')),
                ('observacao', models.CharField(max_length=500, verbose_name='observacao')),
            ],
        ),
    ]
