# Generated by Django 2.2.8 on 2021-05-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='idade',
            field=models.IntegerField(verbose_name='idade'),
        ),
    ]
