# Generated by Django 2.2.8 on 2021-05-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210507_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
    ]
